# Neden Numpy

Numpy önemli bir yapay zeka kütüphanesidir. Tensorflow ya da scikit-learn kütüphanelerinin sahip olduğu fonksiyonlar gibi yapay zekada işi çok kolaylaştıran komutları  olmamasına karşın vektör işlemlerini sağladığı için önemlidir. Yapay zekada vektörleşme kullanılır, bu sayede çok daha daha az for döngüsü kullanılacağı için işlemler çok daha hızlı olur. Örneğin bir python listesindeki her bir elemanın karesini almak için for döngüsüne ihtiyaç duyarken numpy vektörlerinde böyle bir gerek yoktur.

In [1]:
import numpy as np
import time

x1= list(range(1000000)) # 1 milyon boyutlu bir bir python listesi oluşturduk
start1=time.time() # zamanı başlattık
x2=[i**2 for i in x1] # listedeki her bir elemanın karesini for döngüsü kullanarak aldık
time1=time.time()-start1 # yukarıdaki işlemin ne kadar sürdüğünü ölçtük

y1=np.arange(1000000) # 1 milyon boyutlu bir numpy array oluşturduk
y1=np.array(y1,np.int64) # veri tipini değiştirdik, kare alma işleminde hafızadan taşma sorunu olmasın diye
start2=time.time()# zamanı başlattık
y2=y1**2 # vektördeki her bir elemanın karesini aldık
time2=time.time()-start2 # yukarıdaki işlemin ne kadar sürdüğünü ölçtük
print(time1/time2) # Burada ilk işlem ikinci işlemin yaklaşık 80 katı sürüyor.
# for döngüsüne ihtiyaç olmadığı için numpy ile çok daha hızlı sonuçlar alıyoruz. 


164.76255780577262


# Ders 1 Temel Komutlar

In [2]:
import numpy as np # kütüphaneyi dahil ediyoruz.
x=[1,2,3,4] # python listesi oluşturduk
y=np.array(x) # listeyi numpy vektöre dönüştürdük. Ayrıca bunların bir diğer adı ndarray
print(x)
print(y)

print(type(x))
print(type(y))
print("Boyutu:",y.shape)
print("Boyut sayısı:",y.ndim)
print("Toplam eleman sayısı:",y.size)
print("Elemanların veri tipi:",y.dtype)


[1, 2, 3, 4]
[1 2 3 4]
<class 'list'>
<class 'numpy.ndarray'>
Boyutu: (4,)
Boyut sayısı: 1
Toplam eleman sayısı: 4
Elemanların veri tipi: int32


In [3]:
x = np.array(16) # 0 boyutlu matris, skaler 
y = np.array([1, 2, 3, 4, 5])  # 1 boyutlu, matris 
z = np.array([[1, 2, 3], [4, 5, 6]])  # 2 boyutlu matris 
w = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])  # 3 boyutlu matris 
print(x.ndim)
print(y.ndim)
print(z.ndim)
print(w.ndim)

0
1
2
3


In [4]:

x = np.array([1, 2, 3, 4], ndmin=5) # Burada boyut sayısını 5 olarak belirledik

print(x)
print('number of dimensions :', x.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions : 5


In [5]:
y=np.array([0.5,3.7,4.8],dtype=np.int32)
x=np.array([1,2,3,4],dtype=np.float64) # veri tipini float yaptık
print(y)
print(x)

[0 3 4]
[1. 2. 3. 4.]


In [6]:
x=np.array([0,1,2])
x=x.astype(np.complex128) # veri tipini kompleks sayı yaptık
print(x)

[0.+0.j 1.+0.j 2.+0.j]


In [7]:
x=np.sqrt(np.array([0,-4,9],dtype=np.complex128)) # vektörü karekökünü aldık.
# Burada negatif sayının da karekökü olduğu için veri tipi kompleks olmalı
print(x)
print(x.real) # vektördeki sayıların reel kısımları
print(x.imag) # vektördeki sayıların sanal kısımları

[0.+0.j 0.+2.j 3.+0.j]
[0. 0. 3.]
[0. 2. 0.]


In [8]:
x=np.array([1,2])
y= np.array([1.5,2.5])
print(x+y) # burada iki farklı veri tipi olduğu için işlemler üst olan veri tipinde yapılır. Burada float daha üst veri tipi

[2.5 4.5]


In [9]:
x=np.array([0,1,2,3,4,5,6])
np.save('x_array',x) # x vektörünü bu adla kaydettik
y=np.load('x_array.npy') # vekörü yükleyip y'ye atadık
print(y)

[0 1 2 3 4 5 6]


# Ders 2 Özel Vektör ve Matrisler Oluşturma

In [10]:
import numpy as np 
x=np.arange(5)# 0'dan 5'e kadar, 5 dahil değil, 5 elemanlı vektör oluşturduk
print(x)

[0 1 2 3 4]


In [11]:
y=np.arange(4,9)# 4'ten 9'a kadar,9 dahil değil,  vektör oluşturduk
print(y)

[4 5 6 7 8]


In [12]:
z=np.arange(3,23,4) # 3'ten 23'e kadar,23 dahil değil, dörder dörder artan vektör oluşturduk
print(z)

[ 3  7 11 15 19]


In [13]:
x=np.linspace(0,18,7) # 0 ile 18 arasında, 18 dahil, eşit aralıklı 7 tane sayı
print(x)

[ 0.  3.  6.  9. 12. 15. 18.]


In [14]:
y=np.linspace(0,20) # 0 ile 20 arasında 50 tane sayı, kaç tane sayı olacağı söylenmezse varsayılan değer 50
print(y)

[ 0.          0.40816327  0.81632653  1.2244898   1.63265306  2.04081633
  2.44897959  2.85714286  3.26530612  3.67346939  4.08163265  4.48979592
  4.89795918  5.30612245  5.71428571  6.12244898  6.53061224  6.93877551
  7.34693878  7.75510204  8.16326531  8.57142857  8.97959184  9.3877551
  9.79591837 10.20408163 10.6122449  11.02040816 11.42857143 11.83673469
 12.24489796 12.65306122 13.06122449 13.46938776 13.87755102 14.28571429
 14.69387755 15.10204082 15.51020408 15.91836735 16.32653061 16.73469388
 17.14285714 17.55102041 17.95918367 18.36734694 18.7755102  19.18367347
 19.59183673 20.        ]


In [15]:
z=np.linspace(0,20,endpoint=False) # 0 ile 20 arasında 50 tane sayı, 20 dahil değil
print(z)

[ 0.   0.4  0.8  1.2  1.6  2.   2.4  2.8  3.2  3.6  4.   4.4  4.8  5.2
  5.6  6.   6.4  6.8  7.2  7.6  8.   8.4  8.8  9.2  9.6 10.  10.4 10.8
 11.2 11.6 12.  12.4 12.8 13.2 13.6 14.  14.4 14.8 15.2 15.6 16.  16.4
 16.8 17.2 17.6 18.  18.4 18.8 19.2 19.6]


In [16]:
x=np.arange(4)
x=np.reshape(x,(2,2)) # matrisin botuyunu değiştirdik
print(x)
y=np.arange(4).reshape(2,2) # yukarıdaki işlemi tek satırda yaptık
print(y)

[[0 1]
 [2 3]]
[[0 1]
 [2 3]]


In [17]:
x=np.zeros(4) # 0'lardan oluşan 4 boyutlu vektör, veri tipi float64
print(x)

[0. 0. 0. 0.]


In [18]:
y=np.ones(4) # 1'lerden oluşan 4 boyutlu vektör, veri tipi float64
print(y)

[1. 1. 1. 1.]


In [19]:
z=np.zeros((2,3)) # 2x3 boyutunda 0 matrisi
print(z)

[[0. 0. 0.]
 [0. 0. 0.]]


In [20]:
x=np.full((2,3),10)  # 10'lardan oluşan 2x3 boyutunda matris
print(x)
y=10*np.ones((2,3))  # yukarıdaki ile aynı matrisi oluşturuyoruz, veri tipi farklı
print(y)
z=10+np.zeros((2,3))  # yukarıdaki ile aynı matrisi oluşturuyoruz, veri tipi farklı
print(z)

[[10 10 10]
 [10 10 10]]
[[10. 10. 10.]
 [10. 10. 10.]]
[[10. 10. 10.]
 [10. 10. 10.]]


In [21]:
x=np.empty((2,2)) # 2x2 boyutunda değerleri 0'a yakın olan bir matris üretir. 
#Ayrıca daha önce 2x2 boyutunda matris oluşturulmuşsa o matrisi kullanır
print(x)

[[1. 1.]
 [1. 1.]]


In [22]:
x=np.zeros((2,2))
x.fill(5) # x matrisinin tüm değerlerini 5 yapar
print(x)

[[5. 5.]
 [5. 5.]]


In [23]:
x=np.eye(2) # 2x2 boyutunda birim matris oluşturur
print(x)

[[1. 0.]
 [0. 1.]]


In [24]:
y=np.eye(3,2) # 3x2 boyutunda birim matris oluşturur
print(y)

[[1. 0.]
 [0. 1.]
 [0. 0.]]


In [25]:
z=np.eye(3,k=1) # 3x3 boyutunda birim matris oluşturup bu matrisi 1 birim yukarı çıkardık
print(z)

[[0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]]


In [26]:
t=np.eye(3,k=-2) # 3x3 boyutunda birim matris oluşturup bu matrisi 2 birim aşağı indirdik
print(t)

[[0. 0. 0.]
 [0. 0. 0.]
 [1. 0. 0.]]


In [27]:
x=np.identity(2) # 2x2 boyutunda birim matris oluşturduk
print(x)

[[1. 0.]
 [0. 1.]]


In [28]:
x=np.diag([1,2,5])# verilen değerleri matrisin köşegenine sırayla yerleştirir, geri kalan değerler 0 olur
print(x)

[[1 0 0]
 [0 2 0]
 [0 0 5]]


In [29]:
x = np.array([1, 2, 3, 4, 5])
y=x # x matrisini kopyaladık.  Bu şekilde yapınca ikisi aynı adresi paylaşıyorlar.
y[2]=7 # Birinde olan değişiklik diğerini de etkiler
print(x)
print(y)

[1 2 7 4 5]
[1 2 7 4 5]


In [30]:
x = np.array([1, 2, 3, 4, 5])
y=x.copy() # x matrisini kopyaladık.  Bu şekilde yapınca ikisi farklı adresi paylaşıyorlar.
y[2]=7 # Birinde olan değişiklik diğerini etkilemez
print(x)
print(y)

[1 2 3 4 5]
[1 2 7 4 5]


In [31]:
x = np.array([1, 2, 3, 4, 5])
y=x.view() # x matrisini kopyaladık.  Bu şekilde yapınca ikisi aynı adresi paylaşıyorlar.
y[2]=7 # Birinde olan değişiklik diğerini de etkiler
print(x)
print(y)

[1 2 7 4 5]
[1 2 7 4 5]


# Ders 3 Matris İşlemleri-1

In [32]:
x=np.arange(5)
print('ilk eleman: ', x[0]) # vektörün ilk elemanı, indeksler 0 ile başlar 
print('son eleman: ', x[-1]) # vektörün son elemanına -1 ile de  ulaşabilriz

ilk eleman:  0
son eleman:  4


In [33]:
x=np.arange(12).reshape(3,4)
print(x[1,2])  # 1. satırın 2.sütünundaki eleman

6


In [34]:
x=np.arange(6)
y=np.delete(x,[0,2]) # 0.ve 2. elemanları siler
print(y)

[1 3 4 5]


In [35]:
x=np.arange(16).reshape(4,4)
x=np.delete(x,1,axis=0) # 1.satırı siler. axis=1 deseydik sütunu silerdi
print(x)

[[ 0  1  2  3]
 [ 8  9 10 11]
 [12 13 14 15]]


In [36]:
x=np.arange(16).reshape(4,4)
x=np.delete(x,[0,2],axis=1) # 0.ve 2. sütunu siler
print(x)

[[ 1  3]
 [ 5  7]
 [ 9 11]
 [13 15]]


In [37]:
x=np.arange(6)
x=np.append(x,10) # vektörün sonuna 10'u ekler
print(x)
y=np.append(x,[15,16]) # vektörün sonuna 15, 16'yı ekler
print(y)

[ 0  1  2  3  4  5 10]
[ 0  1  2  3  4  5 10 15 16]


In [38]:
x=np.arange(9).reshape(3,3)
x=np.append(x,[[10,20,30]], axis=0) # son satır olarak ekledik
print(x)
y=np.append(x,[[40],[50],[60],[70]],axis=1) # son sütun ekledik
print(y)
# Burada veriye uygun boyutta satır ya da sütun eklemezsek hata alırız. 
# Burada satıra ya da sütuna eklerken tek fark axis değil. Köşeli parantezlerin durumu da farklı. 
# Buna da dikkat edilmesi gerekiyot

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [10 20 30]]
[[ 0  1  2 40]
 [ 3  4  5 50]
 [ 6  7  8 60]
 [10 20 30 70]]


In [39]:
x=np.arange(6)
x= np. insert(x,0,10) # x'in 0. indisine 10'u ekler 
print(x)

[10  0  1  2  3  4  5]


In [40]:
x=np.arange(9).reshape(3,3)
x=np.insert(x,1,[10,20,30],axis=0) # 1. indeksli satıra [10,20,30]'u ekledik
print(x)
y=np.insert(x,0,[40,50,60,70],axis=1) # 0. indeksli sütuna [40,50,60,70]'i ekledik
print(y)

[[ 0  1  2]
 [10 20 30]
 [ 3  4  5]
 [ 6  7  8]]
[[40  0  1  2]
 [50 10 20 30]
 [60  3  4  5]
 [70  6  7  8]]


In [41]:
x=np.arange(3)
y=np.arange(9).reshape(3,3) 
z=np.vstack((x,y)) # x'i y nin tepesine ekler
print(z)
t=np.hstack((x,y.reshape(9,))) # x', y'ye yatay olarak ekler, bunun y'yi uygun boyutlu hale getiriyoruz
print(t)

[[0 1 2]
 [0 1 2]
 [3 4 5]
 [6 7 8]]
[0 1 2 0 1 2 3 4 5 6 7 8]


In [42]:
x = np.array([1, 2, 3])

y = np.array([4, 5, 6])

z = np.concatenate((x, y)) # 2 matrisi birleştirdik

print(z)

[1 2 3 4 5 6]


In [43]:
import numpy as np

x = np.array([[1, 2], [3, 4]])

y = np.array([[5, 6], [7, 8]])

z = np.concatenate((x, y), axis=1) # iki boyutlu iki matrisi birleştirdik

print(z)

[[1 2 5 6]
 [3 4 7 8]]


In [44]:
x = np.array([1, 2, 3])

y = np.array([4, 5, 6])

z = np.stack((x, y), axis=1) # Burada her bir elemanı karşılık gelen eleman ile birleştiriyor. 
# ama her birleşim sonucunu ayrı tutuyor diğer birleşim sonucundan

print(z)

[[1 4]
 [2 5]
 [3 6]]


In [45]:
import numpy as np

x = np.array([1, 2,3])

y = np.array([4, 5,6])

z = np.dstack((x, y)) # Yukarıdakine benzer şekilde birleştirme yapıyor.
# ama bunda çıkan sonucu bir boyutun içine koyup boyut arttırıyor diyebiliriz

print(z)

[[[1 4]
  [2 5]
  [3 6]]]


# Ders 4 Matris Bölme İşlemleri

In [46]:
x=np.arange(10)
print(x[2:6]) # 2.indeksten 6. indekse kadar, 6.indeks dahil değil
print(x[7:]) # 7. indeksten sonraki sona kadar tüm elemanlar, 7. indeks dahil
print(x[:4]) # baştan 4. indekse kadar, 4.indeks dahil değil
print(x[:-1]) # baştan -1. elemana kadar yani son elemana kadar. Son eleman dahil değil

[2 3 4 5]
[7 8 9]
[0 1 2 3]
[0 1 2 3 4 5 6 7 8]


In [47]:
x = np.array([1, 2, 3, 4, 5, 6, 7])

print(x[1:5:2]) # 1. indeskten 5. indekse kadar 2'şer adımla alıyor. 5. indeks dahil değil

[2 4]


In [48]:
x=np.arange(25).reshape(5,5)
print(x)
y=x[0:3,1:4] # 0. indeksten 3.indekse kadar olan satırların 1. indeksten 4.indekse kadar olan sütunları
print(y)
z=x[2:] # 2. indeksli satırdan sonraki tüm satırlar
print(z)
t=x[::]
print(t) #tüm satır ve sütunlar



[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[[ 1  2  3]
 [ 6  7  8]
 [11 12 13]]
[[10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


Eğer matrisleri bu şekilde bölersek hafızada aynı yeri paylaşırlar. 

In [49]:
print(np.shares_memory(x,y)) # eğer hafıza aynı yeri paylaşıyorlarsa True döner

True


In [50]:
x=x=np.arange(16).reshape(4,4)
print(x)
y=np.copy(x [0:3,1:3]) # bu şekilde yaparsak hafızada aynı yeri paylaşmaz
print(y)
print(np.shares_memory(x,y))
z=x[1:2,1:2].copy() # bu da kopyalamanın farklı bir yolu
print(z)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[ 1  2]
 [ 5  6]
 [ 9 10]]
False
[[5]]


In [51]:
x=np.linspace(1,21,11)
y=np.array([2,4,7])
z=x[y] # x'in y'de bulunan elemanlara göre ayrılması. Burada x'in 2., 4. ve 7. indeksteki elemanları alınır
print(x)
print(z)

[ 1.  3.  5.  7.  9. 11. 13. 15. 17. 19. 21.]
[ 5.  9. 15.]


In [52]:
x=np.arange(25).reshape(5,5)
print(x)
y=np.array([1,2])
z=x[y] # 1. ve 2. indeksteki satırlar alınır. z ile x hafızada aynı yeri paylaşmaz
print(z)
print(np.shares_memory(x,z))


[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[[ 5  6  7  8  9]
 [10 11 12 13 14]]
False


In [53]:
x=np.arange(1,7)
y=x[x%2==0] # x'in 2'tam bölünebilen elemanları alınır. x ile y hafızada aynı yeri paylaşmaz.
print(y)
print(np.shares_memory(x,y))

[2 4 6]
False


In [54]:
x = np.array([1, 2, 3, 4, 5, 6,7,8])

y = np.array_split(x, 3) # Matris elemanlarını 3 gruba ayırdık

print(y)

[array([1, 2, 3]), array([4, 5, 6]), array([7, 8])]


In [55]:
import numpy as np

x = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])

y = np.array_split(x, 3) # 2 boyutlu matrisi 3 gruba ayırdık

print(y)

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]


In [56]:
x = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

y = np.hsplit(x, 3) # Burada 3 gruba ayırdık ama gruptaki her elemanı da ayrı bir listenin daha içine aldık

print(y)

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


In [57]:
x = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

y = np.vsplit(x, 3) # Burada 3 gruba ayırdık ama gruptaki her elemanı da ayrı bir listenin daha içine aldık

print(y)

[array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]]), array([[13, 14, 15],
       [16, 17, 18]])]


# Ders 5 Mantık İşlemleri

In [58]:
x=np.array([3, 5, 7])
y=np.array([1, 9, 6])
z=x>y # x'in bir indeksteki elemanı y'deki o indeksteki elemandan büyükse True döner
print(z)
print(np.all(x>y)) # eğer bir tane bile False varsa False döner
print(np.any(x>y)) # en az bir tane True varsa True döner
print(x[x>y]) # x'in bir indeksteki elemanı y'deki o indeksteki elemanından büyükse o elemanları döndürür. Yani şartı sağlayan

[ True False  True]
False
True
[3 7]


In [59]:
x=np.arange(6)
mask=x%2==0 # Bir elemaının 2'ye bölümünden kalan 0'sa True değerini alır mask'ın o elemana karşılık gelen indeksi
print(mask)
print(x[mask]) # x'in, mask'ta True değerine sahip indekslerdeki elemanları

[ True False  True False  True False]
[0 2 4]


In [60]:
x=np.array([3,5,9])
y=np.array([1,5,3])
print(x==y) #Aynı indeksteki eleman eşitse o indise True değilse False atıyor

[False  True False]


In [61]:
x=np.array([1,2])
y=np.array([5,2]) 
print(np.array_equal(x,y)) # İki matris eşitse True döner

False


In [62]:
x = np.array([1, 2, 3, 4, 5, 6, 7, 8])

y = np.where(x%2 == 0) # burada 2'ye tam bölünebilen sayıların indisini atıyoruz

print(y)

(array([1, 3, 5, 7], dtype=int64),)


In [63]:
#np.where'in böyle bir kullanımı daha var
x= np.arange(10)
y=np.where(x<5,2*x,10*x) # eğer bir eleman 5'ten küçükse 2 katını al değilse 10 katını al
print(x)
print(y)

[0 1 2 3 4 5 6 7 8 9]
[ 0  2  4  6  8 50 60 70 80 90]


# Ders 6 Küme İşlemleri

In [64]:
x=np.array([2,5,3,6,9])
y=np.array([6,1,8,7,3])
print(np.intersect1d(x,y)) # Her ikisinde de ortak olan elemanları döner
print(np.setdiff1d(x,y)) # x'de olup y'de olmayan elemanları döner
print(np.union1d(x,y)) # Birleşim kümesi
print(np.in1d(x,y)) # x'in elemanlarına bakar, eğer bu eleman y'de varsa True döner


[3 6]
[2 5 9]
[1 2 3 5 6 7 8 9]
[False False  True  True False]


In [65]:
x=np.array([2,5,3,6,9,4,3,6,5,0]) 
print(np.unique(x)) # bir eleman birden fazla varsa sayısını bire düşürür

[0 2 3 4 5 6 9]


In [66]:
x=np.array([3,3,7,1,2,3,6]) 
print(np.sort(x)) # x'i küçükten büyüğe doğru sıralar

[1 2 3 3 3 6 7]


In [67]:
x=np.array([[3,5,2],[4,8,1],[1,2,3]]) 
print(x)
print(np.sort(x,axis=0)) # her sütunu kendi içinde sıralar
print(np.sort(x,axis=1)) # her satırı kendi içinde sıralar

[[3 5 2]
 [4 8 1]
 [1 2 3]]
[[1 2 1]
 [3 5 2]
 [4 8 3]]
[[2 3 5]
 [1 4 8]
 [1 2 3]]


# Ders 7 Aritmetik İşlemler

In [68]:
x=np.arange(1,6)
y=np.arange(6,11)
print(x)
print(y)
print(x+y) # iki matris toplanır
print(np.add(x,y)) # iki matris toplanır
print(x-y) # x'ten y çıkarılır
print(np.subtract(x,y)) # x'ten y çıkarılır
print(x*y) # x ile y çarpılır
print(np.multiply(x,y)) # x ile y çarpılır
print(x/y) #x, y'ye bölünür
print(np.divide(x,y)) #x, y'ye bölünür
print(np.mod(y,x)) # y'nin x'e göre modu

[1 2 3 4 5]
[ 6  7  8  9 10]
[ 7  9 11 13 15]
[ 7  9 11 13 15]
[-5 -5 -5 -5 -5]
[-5 -5 -5 -5 -5]
[ 6 14 24 36 50]
[ 6 14 24 36 50]
[0.16666667 0.28571429 0.375      0.44444444 0.5       ]
[0.16666667 0.28571429 0.375      0.44444444 0.5       ]
[0 1 2 1 0]


In [69]:
x = np.array([10, 20, 30, 40, 50, 60])
y = np.array([3, 7, 9, 8, 2, 33])

z = np.divmod(x, y) # 2 matris dönüyor. Birisi bölüm diğeri de kalan

print(z)

(array([ 3,  2,  3,  5, 25,  1]), array([ 1,  6,  3,  0,  0, 27]))


In [70]:
x=np.arange(1,6)
print(x)
print(x+3) # x'teki her bir elemana 3 eklenir
print(x*2) # x'teki her bir eleman 3 ile çarpılır

[1 2 3 4 5]
[4 5 6 7 8]
[ 2  4  6  8 10]


In [71]:
x=np.array([0,1,4,9])
print(np.sqrt(x)) # her bir elemanın karekökü
print(np.power(x,3)) # her bir elemanın 3.kuvveti
print(np.exp(x)) # her bir elemanın e üssü


[0. 1. 2. 3.]
[  0   1  64 729]
[1.00000000e+00 2.71828183e+00 5.45981500e+01 8.10308393e+03]


In [72]:
x=np.array([1,4,9])
print(np.log2(x)) # her bir eleman 2 tabanına göre logaritmiği

[0.       2.       3.169925]


In [73]:
x = 4
y = 6

z = np.lcm(x, y) # Sayıların ekoku yani ortak en küçük katı

print(z)

12


In [74]:
import numpy as np

x = np.array([3, 6, 9])

z = np.lcm.reduce(x) # dizideki elemanların ekoku

print(z)

18


In [75]:
x = 4
y = 6

z = np.gcd(x, y) # Sayıların ebobu yani ortak en büyük böleni

print(z)

2


In [76]:
import numpy as np

x = np.array([3, 6, 9])

z = np.gcd.reduce(x) # dizideki elemanların ekoku

print(z)

3


In [77]:
x = np.array([1, 2, 3, 4])

y = np.prod(x) # x'in içindeki elemanların birbirleriyle çarpımı

print(y)

24


In [78]:
x = np.array([1, 2, 3, 4])
y = np.array([5, 6, 7, 8])

z = np.prod([x, y]) # iki vektörün içindeki elemanların birbirleriyle çarpımı

print(z)

40320


In [79]:
x = np.array([1, 2, 3, 4])
y = np.array([5, 6, 7, 8])

z = np.prod([x, y],axis=1) # iki vektörün kendi içindeki elemanlarının çarpımı

print(z)

[  24 1680]


In [80]:
x = np.array([1, 2, 3, 4])

x = np.cumprod(x) # matris elemanlarının kümülatif çarpımı
# Burada her bir eleman kendinden önce gelen sayılarla çarpılıyor.

print(x)

[ 1  2  6 24]


In [81]:
x = np.array([1, 2, 3, 4])
y = np.array([5, 6, 7, 8])

z = np.sum([x, y]) # iki vektörün içindeki elemanların toplamı

print(z)

36


In [82]:
x = np.array([1, 2, 3, 4])
y = np.array([5, 6, 7, 8])

z = np.sum([x, y],axis=1) # her iki vektörün de kendi  içindeki elemanların toplamı

print(z)

[10 26]


In [83]:
x = np.array([1, 2, 3, 4])

x = np.cumsum(x) # matris elemanlarının kümülatif toplamı
# Burada her bir eleman kendinden önce gelen sayılarla toplanıyor.

print(x)

[ 1  3  6 10]


In [84]:
x = np.array([1, 2, 3, 4]) # Burada her bir eleman kendisinden sonraki elemandan çıkarılıyor
y = np.diff(x)  # Burada her bir eleman kendisinden sonraki elemandan çıkarılıyor
# 2-1=1, 3-2=1, 4-3=1

print(y)

[1 1 1]


In [85]:
x = np.array([1, 2, 3, 4]) # Burada her bir eleman kendisinden sonraki elemandan çıkarılıyor


newarr = np.diff(x, n=2) # Bu çıkarma işlemi 2 kere yapılıyor. Yani ilk önce normal çıkarma yapılıp bir matris elde ediliyor
# Sonrasında bu yeni matrise tekrardan çıkarma işlemi bir kez daha yapılıyor



print(y)

[1 1 1]


In [86]:
x = np.trunc([-3.1666, 3.6667]) # ondalık kısım atılır

print(x)

[-3.  3.]


In [87]:
x = np.fix([-3.1666, 3.6667]) # ondalık kısım atılır

print(x)

[-3.  3.]


In [88]:
x = np.around(3.1666, 2) # yuvarlama yapar. Bunu 2 basamağa göre yapar

print(x)

3.17


In [89]:
x = np.floor([-3.1666, 3.6667]) # sayıları kendisinden küçük en büyük sayıya yuvarlar 

print(x)

[-4.  3.]


In [90]:
x = np.ceil([-3.1666, 3.6667]) # sayıları kendisinden büyük en küçük sayıya yuvarlar 

print(x)

[-3.  4.]


In [91]:
x = np.sin(np.pi/2) # Pi/2'nin sin değeri

print(x)

1.0


In [92]:
x = np.array([90, 180, 270, 360])

z= np.deg2rad(x) # buradaki değerleri dereceden radyan cinsine çeviriyor. 

print(z)

[1.57079633 3.14159265 4.71238898 6.28318531]


In [93]:
x = np.array([np.pi/2, np.pi, 1.5*np.pi, 2*np.pi])

z = np.rad2deg(x) # Radyan cinsinden dereceye çevirdik

print(z)

[ 90. 180. 270. 360.]


In [94]:
x = np.arcsin(1.0) # 1.0'ın arcsin değeri yani sin değeri 1.0 olan açının radaynı

print(x)

1.5707963267948966


In [95]:
x = np.hypot(5, 12) # Bu iki değerinin hipotenüs toplamını buluyor

print(x)

13.0


In [96]:
x = np.sinh(np.pi/2) # sinh değeri

print(x)

2.3012989023072947


# Ders 8 Matris İşlemleri-2

In [97]:
x=np.arange(9).reshape(3,3)
print(x)
print(np.sum(x)) # tüm elemanların toplamı
print(np.sum(x,axis=1)) # her bir satırın kendi içinde toplamı
print(np.sum(x,axis=0)) # her bir sütunun kendi içinde toplamı
print(x.min()) # minimum eleman
print(x.max()) # maksimum eleman
print(x.argmin()) # minimum elemanın indisi
print(x.argmax()) # maksimum elemanın indisi

[[0 1 2]
 [3 4 5]
 [6 7 8]]
36
[ 3 12 21]
[ 9 12 15]
0
8
0
8


In [98]:
x=np.array([2,4,4,8,4,1,4,9])
print(x.mean()) #aritmetik ortalama
print(np.median(x)) # medyan
print(x.std()) # standart sapma

4.5
4.0
2.5495097567963922


In [99]:
x=np.array([[3,5,2],[4,8,1],[1,2,3]]) 
print(x)
print(x.mean(axis=0)) # her sütunun kendi içinde aritmetik ortalaması
print(np.median(x,axis=1)) # her satırın kendi içinde medyanı

[[3 5 2]
 [4 8 1]
 [1 2 3]]
[2.66666667 5.         2.        ]
[3. 4. 2.]


# Ders 9 Broadcasting

Numpy kütüphanesinde aritmetik işlem yaparken iki matrisin boyutları aynı olmalıdır. Fakat bunun bir istisnası var. Eğer eşit olmayan boyutlarından birinin boyutu 1 ise bu durumda aritmatik işlem yapılabilir. Örneğin 3x3 boyutlu bir matris ile 1x3 boyutlu matris toplanabilir. Burada 4x1 matrisi toplamadan önce 4x3 yapılır. Bunu python kendisi yapıyor bizim ek bir işlem yapmamıza gerek yok. Bu olaya broadcasting adı verilir. Fakat 5x1 matrisi ile 4x1 matrisi toplanamaz

In [100]:
x=np.arange(9).reshape(3,3)
y=np.arange(1,4).reshape(1,3)
print(x)
print(y)
print(x+y) 
# Toplama esnasında y matrisi buna dönüşüyor. Fakat toplama btince eski haline dönüyor
# [[1 2 3]
#  [1 2 3]
#  [1 2 3]]

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[1 2 3]]
[[ 1  3  5]
 [ 4  6  8]
 [ 7  9 11]]


In [101]:
x=np.arange(6,9).reshape(3,1)
y=np.arange(1,4).reshape(1,3)
print(x)
print(y)
print(x+y)


[[6]
 [7]
 [8]]
[[1 2 3]]
[[ 7  8  9]
 [ 8  9 10]
 [ 9 10 11]]


In [102]:
# Burada hata alacaksınız çünkü bu iki matris broad castinge uygun değil

x=np.arange(6,10).reshape(4,1)
y=np.arange(1,6).reshape(5,1)
print(x)
print(y)
print(x+y)

[[6]
 [7]
 [8]
 [9]]
[[1]
 [2]
 [3]
 [4]
 [5]]


ValueError: operands could not be broadcast together with shapes (4,1) (5,1) 

# Ders 10 Random

In [103]:
x = np.random.randint(10) # 0 ile 10 arasında rastgele bir tamsayı döner. 10 dahil değil

print(x)

5


In [104]:
x=np.random.randint(2,9,(3,2)) # 3x2 boyutunda 2 ile 9 arasında rastgele tam sayılarıdan oluşan matris, 9 dahil değil
print(x)

[[6 7]
 [3 2]
 [4 6]]


In [105]:
x=np.random.random((2,2)) # 2x2 boyutunda 0 ile 1 arasındaki rastgele değerlerden oluşan matris. 1 dahil değil
print(x)

[[0.59188458 0.67527719]
 [0.96241679 0.79018749]]


In [106]:
x = np.random.rand()  # 0 ile 1 arasında bir rastgele sayı üretir

print(x)

0.17113375173871148


In [107]:
x =np.random.choice([3, 5, 7, 9]) # Bu listeden rastgele bir eleman seçer

print(x)

5


In [108]:
x = np.random.choice([2, 5, 6, 9], size=(2, 4)) # 2x4 boyutunda bu listenin elemanlarından bir matris oluşturur

print(x)

[[2 2 5 2]
 [9 5 2 5]]


In [109]:
#Burada 10 elemanlı bir vektör oluşturuyor. ilk listedeki elemanları kullanıyor. 
# p ise bu listedeki elemanların yeni vektörde ne kadar olasılık ile olacağını gösteren bir başka liste
# Ama illa bu bunun aynısı dağılıma sahip olmuyor.
x = np.random.choice([1, 4, 5, 9], p=[0.1, 0.3, 0.6, 0.0], size=(10))

print(x)

[4 5 5 5 4 5 4 1 4 5]


In [110]:
# Yukarıdaki işlemi 3x5 boyutlarındaki bir matris oluşması için için modifiye ettik
x = np.random.choice([1, 4, 5, 9], p=[0.1, 0.3, 0.6, 0.0], size=(3,5))

print(x)

[[5 4 4 5 5]
 [5 4 4 5 5]
 [5 1 5 4 4]]


In [111]:
x = np.array([1, 2, 3, 4, 5])

np.random.shuffle(x) # elemanların yerini değiştirdik. Vektörü karıştırdık da diyebiliriz

print(x)

[4 1 5 2 3]


In [112]:
x = np.array([1, 2, 3, 4, 5])
np.random.permutation(x) # Bu şekilde de elemanları karıştırıdık. Ama bu işlem matrisin kendisini değiştirimiyor
print(x)
print(np.random.permutation(x))

[1 2 3 4 5]
[5 3 4 1 2]


In [113]:
x = np.random.normal(size=(2, 3)) # Normal dağılıma sahip 2x3 boyutlarında bir matris

print(x)  

[[ 0.13547153 -0.31091849 -1.64131674]
 [-0.98478746  0.79285678 -0.47716114]]


In [114]:
x = np.random.normal(loc=1, scale=2,size=(2, 3)) # 
#ortalaması 1 standart sapması 2 olan normal dağılıma sahip 2x3 boyutlarında bir matris

print(x)  

[[ 0.90957993 -5.6780113  -3.43275932]
 [ 3.77013287  3.05525456  0.02141478]]


In [115]:
#binom dağılımına sahip bir vektör
x = np.random.binomial(n=10, p=0.5, size=10)
print(x)  

[5 3 8 5 5 5 5 6 6 3]


In [116]:
# poisson dağılıma sahip bir matris
x = np.random.poisson(lam=2, size=10)

print(x)

[2 1 2 3 2 0 1 1 1 3]


In [117]:
# uniform dağılıma sahip bir matris
x = np.random.uniform(size=(2, 3))

print(x)

[[0.95472968 0.62751746 0.53656923]
 [0.13566286 0.97878373 0.79662046]]
